-- Phase 4 / 01_setup.sql  (generated by scripts/build_snowflake_scripts.py; do not edit by hand)
-- Run as a role that can create databases (the trial's ACCOUNTADMIN is fine).
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS MOTION_INTENT;
CREATE SCHEMA IF NOT EXISTS MOTION_INTENT.PIPELINE;
USE SCHEMA MOTION_INTENT.PIPELINE;

-- CSV columns are mapped BY POSITION, so each table below lists its columns in the file's column order.
-- Renamed because they are reserved words: group -> take_group, false -> false_boundaries.
CREATE OR REPLACE FILE FORMAT motion_csv TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('') EMPTY_FIELD_AS_NULL = TRUE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;
CREATE OR REPLACE FILE FORMAT motion_parquet TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS motion_stage FILE_FORMAT = motion_csv;

CREATE OR REPLACE TABLE takes (
    take VARCHAR,
    take_group VARCHAR,
    n_frames BIGINT,
    duration_s DOUBLE,
    mean_fps DOUBLE,
    frames_not_detected BIGINT,
    fraction_not_detected DOUBLE,
    left_handedness_frames BIGINT,
    n_ground_truth_segments BIGINT,
    n_events BIGINT
);

CREATE OR REPLACE TABLE events (
    take VARCHAR,
    take_group VARCHAR,
    event_idx BIGINT,
    label VARCHAR,
    start_s DOUBLE,
    end_s DOUBLE,
    duration_s DOUBLE,
    n_frames BIGINT,
    mean_speed DOUBLE,
    mean_aperture DOUBLE,
    mean_confidence DOUBLE,
    frac_missing DOUBLE,
    model_version VARCHAR
);

CREATE OR REPLACE TABLE ground_truth (
    take VARCHAR,
    cycle BIGINT,
    label VARCHAR,
    start_s DOUBLE,
    end_s DOUBLE,
    source VARCHAR
);

CREATE OR REPLACE TABLE signals (
    take VARCHAR,
    t_s DOUBLE,
    speed DOUBLE,
    aperture DOUBLE,
    aperture_slope DOUBLE,
    progress DOUBLE,
    progress_rate DOUBLE,
    offaxis DOUBLE,
    offaxis_rate DOUBLE,
    height DOUBLE,
    vertical_velocity DOUBLE,
    missing BOOLEAN,
    interpolated BOOLEAN,
    predicted_label VARCHAR,
    ground_truth_label VARCHAR
);

CREATE OR REPLACE TABLE frames (
    take VARCHAR,
    frame_idx BIGINT,
    t_s DOUBLE,
    detected BOOLEAN,
    wrist_x DOUBLE,
    wrist_y DOUBLE,
    thumb_tip_x DOUBLE,
    thumb_tip_y DOUBLE,
    index_tip_x DOUBLE,
    index_tip_y DOUBLE,
    handedness VARCHAR,
    handedness_score DOUBLE
);

CREATE OR REPLACE TABLE scores (
    take VARCHAR,
    take_group VARCHAR,
    tolerance_s DOUBLE,
    scope VARCHAR,
    n_true DOUBLE,
    n_pred DOUBLE,
    n_matched DOUBLE,
    recall DOUBLE,
    precision DOUBLE,
    mae_matched_s DOUBLE,
    missed DOUBLE,
    false_boundaries DOUBLE,
    chance_uniform_recall DOUBLE,
    chance_uniform_precision DOUBLE,
    chance_random_recall DOUBLE,
    chance_random_precision DOUBLE,
    n_frames BIGINT,
    n_unlabelled BIGINT,
    frame_accuracy DOUBLE,
    acc_REST DOUBLE,
    n_REST BIGINT,
    acc_REACH DOUBLE,
    n_REACH BIGINT,
    acc_GRASP DOUBLE,
    n_GRASP BIGINT,
    acc_HOLD DOUBLE,
    n_HOLD BIGINT,
    acc_RELEASE DOUBLE,
    n_RELEASE BIGINT,
    acc_RETRACT DOUBLE,
    n_RETRACT BIGINT,
    balanced_accuracy DOUBLE,
    majority_baseline DOUBLE,
    tolerant_accuracy DOUBLE
);

CREATE OR REPLACE TABLE raw_keypoints (
    take VARCHAR,
    frame_idx BIGINT,
    timestamp_ms BIGINT,
    keypoint_id BIGINT,
    x DOUBLE,
    y DOUBLE,
    z DOUBLE,
    world_x DOUBLE,
    world_y DOUBLE,
    world_z DOUBLE,
    detected BOOLEAN,
    handedness VARCHAR,
    handedness_score DOUBLE
);
