"""Generate snowflake/01_setup.sql, 02_load.sql and 03_verify.sql from data/export (manifest + CSV headers + raw
per-take counts), so table definitions always match the files and no expected count is typed by hand.

SQL used is portable (Snowflake and DuckDB), so tests/test_snowflake_sql.py can execute the same scripts locally.
"""
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
EXP, OUT = ROOT / "data" / "export", ROOT / "snowflake"
RENAME = {"group": "take_group", "false": "false_boundaries"}   # reserved words in Snowflake
CSV_TABLES = ["takes", "events", "ground_truth", "signals", "frames", "scores"]
SQL_TYPE = {"int64": "BIGINT", "float64": "DOUBLE", "bool": "BOOLEAN"}
RESERVED = {"group", "false", "true", "table", "order", "select", "from", "where", "start", "end", "all", "any", "case",
            "check", "column", "default", "desc", "distinct", "else", "exists", "for", "full", "having", "in", "into", "is",
            "join", "left", "like", "not", "null", "on", "or", "right", "row", "rows", "schema", "set", "some", "then", "to",
            "union", "unique", "using", "values", "when", "with", "qualify", "sample"}


def columns(table: str):
    if table == "raw_keypoints":
        df = pd.read_parquet(EXP / "raw_keypoints.parquet")
    else:
        df = pd.read_csv(EXP / f"{table}.csv")
    cols = []
    for name, dt in df.dtypes.items():
        t = SQL_TYPE.get(str(dt), "VARCHAR")
        cols.append((RENAME.get(name, name), t))
    return cols


def ddl(table: str) -> str:
    body = ",\n".join(f"    {n} {t}" for n, t in columns(table))
    return f"CREATE OR REPLACE TABLE {table} (\n{body}\n);"


def build() -> dict[str, str]:
    man = json.loads((EXP / "manifest.json").read_text())["files"]
    rows = {k.split(".")[0]: v["rows"] for k, v in man.items()}
    takes = pd.read_csv(EXP / "takes.csv")
    raw = pd.read_parquet(EXP / "raw_keypoints.parquet")["take"].value_counts().to_dict()
    gt = pd.read_csv(EXP / "ground_truth.csv")["take"].value_counts().to_dict()
    sig = pd.read_csv(EXP / "signals.csv")["take"].value_counts().to_dict()

    setup = ["-- Phase 4 / 01_setup.sql  (generated by scripts/build_snowflake_scripts.py; do not edit by hand)",
             "-- Run as a role that can create databases (the trial's ACCOUNTADMIN is fine).",
             "USE ROLE ACCOUNTADMIN;",
             "CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;",
             "USE WAREHOUSE COMPUTE_WH;",
             "CREATE DATABASE IF NOT EXISTS MOTION_INTENT;",
             "CREATE SCHEMA IF NOT EXISTS MOTION_INTENT.PIPELINE;",
             "USE SCHEMA MOTION_INTENT.PIPELINE;", "",
             "-- CSV columns are mapped BY POSITION, so each table below lists its columns in the file's column order.",
             "-- Renamed because they are reserved words: group -> take_group, false -> false_boundaries.",
             "CREATE OR REPLACE FILE FORMAT motion_csv TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"'",
             "    NULL_IF = ('') EMPTY_FIELD_AS_NULL = TRUE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;",
             "CREATE OR REPLACE FILE FORMAT motion_parquet TYPE = PARQUET;",
             "CREATE STAGE IF NOT EXISTS motion_stage FILE_FORMAT = motion_csv;", ""]
    setup += [ddl(t) + "\n" for t in CSV_TABLES + ["raw_keypoints"]]

    load = ["-- Phase 4 / 02_load.sql  (generated). Upload the 7 files from data/export/ to @motion_stage first (see snowflake/README.md). Patterns match the file with or without a .gz suffix.",
            "USE SCHEMA MOTION_INTENT.PIPELINE;", "LIST @motion_stage;", ""]
    for t in CSV_TABLES:
        load += [f"TRUNCATE TABLE {t};",
                 f"COPY INTO {t} FROM @motion_stage PATTERN = '.*{t}[.]csv([.]gz)?' FILE_FORMAT = (FORMAT_NAME = motion_csv) ON_ERROR = ABORT_STATEMENT FORCE = TRUE;", ""]
    load += ["TRUNCATE TABLE raw_keypoints;",
             "COPY INTO raw_keypoints FROM @motion_stage PATTERN = '.*raw_keypoints[.]parquet' FILE_FORMAT = (FORMAT_NAME = motion_parquet)",
             "    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = ABORT_STATEMENT FORCE = TRUE;", "",
             "-- Summary: if any count below is 0, the COPY found no file. Run 00_diagnose.sql.",
             "SELECT 'takes' AS table_name, COUNT(*) AS loaded_rows FROM takes UNION ALL SELECT 'events', COUNT(*) FROM events UNION ALL",
             "SELECT 'ground_truth', COUNT(*) FROM ground_truth UNION ALL SELECT 'signals', COUNT(*) FROM signals UNION ALL",
             "SELECT 'frames', COUNT(*) FROM frames UNION ALL SELECT 'scores', COUNT(*) FROM scores UNION ALL",
             "SELECT 'raw_keypoints', COUNT(*) FROM raw_keypoints;", ""]

    tbl_vals = ",\n        ".join(f"('{t}', {rows[t]})" for t in CSV_TABLES + ["raw_keypoints"])
    pertake = lambda f: ",\n        ".join(f"('{r.take}', {f(r)})" for r in takes.itertuples())
    verify = f"""-- Phase 4 / 03_verify.sql  (generated). Expected values come from data/export/manifest.json and the per-take
-- metadata, NOT from the tables being checked. Every row must say PASS.
USE SCHEMA MOTION_INTENT.PIPELINE;

WITH expected AS (
    SELECT * FROM (VALUES
        {tbl_vals}
    ) AS v(table_name, expected_rows)
), actual AS (
    SELECT 'takes' AS table_name, COUNT(*) AS actual_rows FROM takes UNION ALL
    SELECT 'events', COUNT(*) FROM events UNION ALL
    SELECT 'ground_truth', COUNT(*) FROM ground_truth UNION ALL
    SELECT 'signals', COUNT(*) FROM signals UNION ALL
    SELECT 'frames', COUNT(*) FROM frames UNION ALL
    SELECT 'scores', COUNT(*) FROM scores UNION ALL
    SELECT 'raw_keypoints', COUNT(*) FROM raw_keypoints
)
SELECT 'row count: ' || e.table_name AS check_name, e.expected_rows AS expected, a.actual_rows AS actual,
       CASE WHEN e.expected_rows = a.actual_rows THEN 'PASS' ELSE 'FAIL' END AS status
FROM expected e JOIN actual a ON a.table_name = e.table_name

UNION ALL
SELECT 'events per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: r.n_events)}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, COUNT(*) AS n FROM events GROUP BY take) c ON c.take = x.take

UNION ALL
SELECT 'frames per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: r.n_frames)}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, COUNT(*) AS n FROM frames GROUP BY take) c ON c.take = x.take

UNION ALL
SELECT 'raw keypoint rows per take (21 x frames): ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: raw[r.take])}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, COUNT(*) AS n FROM raw_keypoints GROUP BY take) c ON c.take = x.take

UNION ALL
SELECT 'signal rows per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: sig[r.take])}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, COUNT(*) AS n FROM signals GROUP BY take) c ON c.take = x.take

UNION ALL
SELECT 'ground-truth segments per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: gt[r.take])}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, COUNT(*) AS n FROM ground_truth GROUP BY take) c ON c.take = x.take

UNION ALL
-- every video frame belongs to exactly one event
SELECT 'sum of event n_frames per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: r.n_frames)}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, SUM(n_frames) AS n FROM events GROUP BY take) c ON c.take = x.take

UNION ALL
SELECT 'undetected frames per take: ' || x.take, x.exp, COALESCE(c.n, 0), CASE WHEN x.exp = COALESCE(c.n, 0) THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT * FROM (VALUES
        {pertake(lambda r: r.frames_not_detected)}
    ) AS v(take, exp)) x LEFT JOIN (SELECT take, SUM(CASE WHEN detected THEN 0 ELSE 1 END) AS n FROM frames GROUP BY take) c ON c.take = x.take

UNION ALL
-- events are contiguous: each start equals the previous end, and every take starts at 0
SELECT 'event gaps or overlaps (rows)', 0, COUNT(*), CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT start_s, LAG(end_s) OVER (PARTITION BY take ORDER BY event_idx) AS prev_end, event_idx FROM events) g
WHERE event_idx > 0 AND ABS(start_s - prev_end) > 0.000001

UNION ALL
SELECT 'takes not starting at 0 s', 0, COUNT(*), CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT take, MIN(start_s) AS s FROM events GROUP BY take) m WHERE s <> 0

UNION ALL
SELECT 'NULLs in events key columns', 0, COUNT(*), CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM events WHERE take IS NULL OR label IS NULL OR start_s IS NULL OR end_s IS NULL OR duration_s IS NULL

UNION ALL
SELECT 'detected raw keypoints with NULL coordinates', 0, COUNT(*), CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM raw_keypoints WHERE detected AND (x IS NULL OR y IS NULL OR z IS NULL)

ORDER BY 1;
"""
    fingerprint = """-- Phase 4 / 04_fingerprint.sql  (generated, OPTIONAL). Value-level check: row counts can match while values are wrong
-- (a mis-parsed boolean, a truncated number). Each row is one aggregate over loaded data; the expected values come from the
-- source files (snowflake/expected_results/fingerprint.csv). Sums are rounded to 4 decimals.
USE SCHEMA MOTION_INTENT.PIPELINE;

SELECT table_name, take, metric, value FROM (
    SELECT 'raw_keypoints' AS table_name, take, 'sum_x' AS metric, ROUND(SUM(x), 4) AS value FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_y', ROUND(SUM(y), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_z', ROUND(SUM(z), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_world_x', ROUND(SUM(world_x), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_world_y', ROUND(SUM(world_y), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_world_z', ROUND(SUM(world_z), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_handedness_score', ROUND(SUM(handedness_score), 4) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'detected_rows', SUM(CASE WHEN detected THEN 1 ELSE 0 END) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'left_handed_rows', SUM(CASE WHEN handedness = 'Left' THEN 1 ELSE 0 END) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_timestamp_ms', SUM(timestamp_ms) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'raw_keypoints', take, 'sum_keypoint_id', SUM(keypoint_id) FROM raw_keypoints GROUP BY take
    UNION ALL SELECT 'frames', take, 'sum_wrist_x', ROUND(SUM(wrist_x), 4) FROM frames GROUP BY take
    UNION ALL SELECT 'frames', take, 'sum_wrist_y', ROUND(SUM(wrist_y), 4) FROM frames GROUP BY take
    UNION ALL SELECT 'frames', take, 'sum_thumb_tip_x', ROUND(SUM(thumb_tip_x), 4) FROM frames GROUP BY take
    UNION ALL SELECT 'frames', take, 'sum_index_tip_y', ROUND(SUM(index_tip_y), 4) FROM frames GROUP BY take
    UNION ALL SELECT 'frames', take, 'sum_t_s', ROUND(SUM(t_s), 4) FROM frames GROUP BY take
    UNION ALL SELECT 'frames', take, 'detected_frames', SUM(CASE WHEN detected THEN 1 ELSE 0 END) FROM frames GROUP BY take
    UNION ALL SELECT 'signals', take, 'sum_speed', ROUND(SUM(speed), 4) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'sum_aperture', ROUND(SUM(aperture), 4) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'sum_progress', ROUND(SUM(progress), 4) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'sum_height', ROUND(SUM(height), 4) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'missing_samples', SUM(CASE WHEN missing THEN 1 ELSE 0 END) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'interpolated_samples', SUM(CASE WHEN interpolated THEN 1 ELSE 0 END) FROM signals GROUP BY take
    UNION ALL SELECT 'signals', take, 'null_ground_truth_labels', SUM(CASE WHEN ground_truth_label IS NULL THEN 1 ELSE 0 END) FROM signals GROUP BY take
    UNION ALL SELECT 'events', take, 'sum_duration_s', ROUND(SUM(duration_s), 4) FROM events GROUP BY take
    UNION ALL SELECT 'events', take, 'sum_mean_speed', ROUND(SUM(mean_speed), 4) FROM events GROUP BY take
    UNION ALL SELECT 'events', take, 'sum_mean_aperture', ROUND(SUM(mean_aperture), 4) FROM events GROUP BY take
    UNION ALL SELECT 'events', take, 'sum_frac_missing', ROUND(SUM(frac_missing), 4) FROM events GROUP BY take
    UNION ALL SELECT 'ground_truth', take, 'sum_start_s', ROUND(SUM(start_s), 4) FROM ground_truth GROUP BY take
    UNION ALL SELECT 'ground_truth', take, 'sum_end_s', ROUND(SUM(end_s), 4) FROM ground_truth GROUP BY take
    UNION ALL SELECT 'ground_truth', take, 'max_cycle', MAX(cycle) FROM ground_truth GROUP BY take
    UNION ALL SELECT 'takes', take, 'n_frames', n_frames FROM takes
    UNION ALL SELECT 'takes', take, 'duration_s', ROUND(duration_s, 4) FROM takes
    UNION ALL SELECT 'takes', take, 'fraction_not_detected', ROUND(fraction_not_detected, 6) FROM takes
    UNION ALL SELECT 'scores', take, 'sum_frame_accuracy', ROUND(SUM(frame_accuracy), 6) FROM scores GROUP BY take
    UNION ALL SELECT 'scores', take, 'sum_balanced_accuracy', ROUND(SUM(balanced_accuracy), 6) FROM scores GROUP BY take
) f
ORDER BY table_name, metric, take;
"""
    tables = CSV_TABLES + ["raw_keypoints"]
    hist = "\nUNION ALL\n".join(
        f"SELECT '{t}' AS table_name, file_name, status, row_count, row_parsed, first_error_message, first_error_line_number\n"
        f"FROM TABLE(MOTION_INTENT.INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME => '{t.upper()}', START_TIME => DATEADD(hours, -24, CURRENT_TIMESTAMP())))"
        for t in tables)
    diagnose = f"""-- Phase 4 / 00_diagnose.sql  (generated). Snowflake-only. Run each numbered statement on its own and read the result.
-- Use this when 03_verify.sql shows 0 rows loaded.

-- 1. Which role / warehouse / database / schema is this worksheet using? Expect MOTION_INTENT and PIPELINE, and a warehouse name.
SELECT CURRENT_ROLE() AS role, CURRENT_WAREHOUSE() AS warehouse, CURRENT_DATABASE() AS db, CURRENT_SCHEMA() AS schema_name;

-- 2. Which MOTION_STAGE stages exist? If you see more than one (another database or schema), your upload may have gone to the wrong one.
SHOW STAGES LIKE 'MOTION_STAGE' IN ACCOUNT;

-- 3. What is inside the stage? Expect 7 files: takes, events, ground_truth, signals, frames, scores (csv) and raw_keypoints.parquet.
--    No rows here = the files were never uploaded to THIS stage.
LIST @MOTION_INTENT.PIPELINE.motion_stage;

-- 4. Row counts right now (all 0 = nothing loaded, or 01_setup.sql was re-run after loading, which recreates empty tables).
SELECT 'takes' AS table_name, COUNT(*) AS n FROM MOTION_INTENT.PIPELINE.takes UNION ALL SELECT 'events', COUNT(*) FROM MOTION_INTENT.PIPELINE.events UNION ALL
SELECT 'signals', COUNT(*) FROM MOTION_INTENT.PIPELINE.signals UNION ALL SELECT 'raw_keypoints', COUNT(*) FROM MOTION_INTENT.PIPELINE.raw_keypoints;

-- 5. What did each COPY do in the last 24 hours? One row per file loaded. No rows = the COPY matched no file.
--    status LOAD_FAILED / PARTIALLY_LOADED shows the error text.
{hist}
ORDER BY 1, 2;

-- 6. Dry run (loads nothing): should return 5 parsed rows. An empty result = the PATTERN matched no file in the stage.
COPY INTO MOTION_INTENT.PIPELINE.events FROM @MOTION_INTENT.PIPELINE.motion_stage PATTERN = '.*events[.]csv([.]gz)?'
    FILE_FORMAT = (FORMAT_NAME = MOTION_INTENT.PIPELINE.motion_csv) VALIDATION_MODE = RETURN_5_ROWS;
"""
    return {"00_diagnose.sql": diagnose, "04_fingerprint.sql": fingerprint, "01_setup.sql": "\n".join(setup), "02_load.sql": "\n".join(load), "03_verify.sql": verify}


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    for name, text in build().items():
        (OUT / name).write_text(text)
        print("wrote", OUT / name, len(text.splitlines()), "lines")
