"""Generate snowflake/sanity_check_checklist.md: concrete timestamps to check against the videos, taken from the exported
events and ground truth (so nothing is typed by hand)."""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
EXP = ROOT / "data" / "export"
ORDER = {("REST", "REACH"), ("REACH", "GRASP"), ("GRASP", "HOLD"), ("HOLD", "RELEASE"), ("RELEASE", "RETRACT"), ("RETRACT", "REST")}
f = lambda v: f"{v:.2f}"


def build() -> str:
    ev = pd.read_csv(EXP / "events.csv").rename(columns={"group": "take_group"})
    gt = pd.read_csv(EXP / "ground_truth.csv")
    ev = ev.sort_values(["take", "event_idx"]).reset_index(drop=True)
    L = []
    w = L.append
    w("# Sanity check: query results vs the videos\n")
    w("Generated by `scripts/make_sanity_checklist.py` from `data/export/`. Fill in the **Seen** columns, then tell the assistant the outcome.\n")
    w("## 0. How to look\n")
    w("- Open the overlay clip `evidence/vidN_overlay.mp4` in QuickTime (or VLC). The top-left label reads `vidN f=<frame> t=<seconds>s`; **use that `t=`, not the player's clock** (the video has variable frame rate).")
    w("- Step one frame at a time with the left/right arrow keys. A clip shows the hand skeleton, not the phase names; the phases are in the tables below.")
    w("- Boundary rules (same ones used for the hand labelling): REST>REACH the hand leaves A; REACH>GRASP fingers start closing; GRASP>HOLD the lift ends and the object stops; HOLD>RELEASE the object touches the table and fingers start opening; RELEASE>RETRACT the hand starts back toward A; RETRACT>REST the hand is on A and stopped.")
    w("- **Tolerance: a boundary within 0.1 s of the listed time counts as correct** (the project's scoring tolerance).")
    w("- For the detected-vs-labelled picture, open `evidence/phase2_v2/vidN_segmentation.png` (top strip = hand-labelled, second strip = detected).")
    w("- What a disagreement means: the Snowflake numbers are already proven to equal the pipeline's events (see `snowflake/README.md`). This check asks whether the **events themselves** match what happened on camera. A mismatch is therefore a finding about the segmenter or the labels, not about Snowflake. Mismatches that match the *Known explanation* column in section C2, or the limits listed in section E, are expected.\n")

    w("## A. Query 3: time between consecutive reaches (cycle time)\n")
    w("For each time, scrub to it and confirm the hand has just left the home mark A. Cycle time is the difference between consecutive times.\n")
    w("| Take | Reach start times (s) | Cycle times (s) | Seen: hand leaves A at each time (Y/N) | Notes |\n|---|---|---|---|---|")
    for t, g in ev[ev["label"] == "REACH"].groupby("take"):
        s = g["start_s"].tolist()
        w(f"| {t} | {', '.join(f(x) for x in s)} | {', '.join(f(b - a) for a, b in zip(s, s[1:]))} | | |")
    w("\nGut check without scrubbing: clean takes feel like about 10 to 12 s per cycle (vid3 a little under 9), the fast take about 2.5 s, the hard take 6 to 9 s.\n")

    w("## B. Query 1: event durations\n")
    w("Pick the listed events, scrub to the start and end times, and confirm the phase begins and ends there (within 0.1 s) and that the length feels right.\n")
    w("| Take | Phase | Start (s) | End (s) | Length (s) | Why this one | Seen: start OK / end OK |\n|---|---|---|---|---|---|---|")
    for kind, labels in (("clean", ["HOLD", "RELEASE"]), ("fast", ["REACH", "GRASP"]), ("hard", ["GRASP", "RELEASE"])):
        for lab in labels:
            g = ev[(ev["take_group"] == kind) & (ev["label"] == lab)]
            for why, r in (("longest " + lab + " of this kind", g.loc[g["duration_s"].idxmax()]), ("shortest " + lab + " of this kind", g.loc[g["duration_s"].idxmin()])):
                w(f"| {r['take']} | {r['label']} | {f(r['start_s'])} | {f(r['end_s'])} | {f(r['duration_s'])} | {why} | |")
    w("")

    w("## C. Query 4: phase order\n")
    w("**C1. Clean takes follow the protocol order in every cycle.** Watch vid1 once from start to end and write down the phases you see in each of its 3 cycles: REST, REACH, GRASP, HOLD, RELEASE, RETRACT, REST. Seen: ______\n")
    c4 = gt[(gt["take"] == "vid5") & (gt["cycle"] == 4) & (gt["label"] == "GRASP")].iloc[0]
    off = []
    for t, g in ev.groupby("take"):
        g = g.reset_index(drop=True)
        for i in range(len(g) - 1):
            if (g.loc[i, "label"], g.loc[i + 1, "label"]) not in ORDER:
                off.append((t, g.loc[i, "label"], g.loc[i + 1, "label"], g.loc[i + 1, "start_s"], g.loc[i, "start_s"], g.loc[i + 1, "end_s"]))
    w("**C2. Transitions that break the protocol order.** Scrub to each time and write what actually happens.\n")
    w("| Take | Detected transition | At (s) | Known explanation | Seen: what happens in the video |\n|---|---|---|---|---|")
    for t, a, b, at, s0, e1 in off:
        if t == "vid4":
            exp = "the real RELEASE (about 0.13 s: object set down, fingers open) was not detected, so HOLD runs straight into RETRACT. Expect to SEE a release."
        else:
            exp = f"inside the hand-labelled cycle 4 GRASP ({f(c4['start_s'])} to {f(c4['end_s'])} s, hand turned so the ball is hidden). Expect to see the hand at the ball, never resting on the home mark A."
        w(f"| {t} | {a} > {b} | {f(at)} | {exp} | |")
    w("")
    w("**C3. The fast take's missing RELEASE is real in the video, not a recording gap.** The hand-labelled RELEASE times in vid4 are:\n")
    w("| Take | Hand-labelled RELEASE (start to end, s) | Seen: fingers open / object set down here (Y/N) |\n|---|---|---|")
    for r in gt[(gt["take"] == "vid4") & (gt["label"] == "RELEASE")].itertuples():
        w(f"| vid4 | {f(r.start_s)} to {f(r.end_s)} | |")
    w("")

    w("## D. Query 2: most ambiguous take\n")
    w("Ambiguous = shorter than 0.3 s, or mean phase probability below 0.7. Query 2 ranks vid5 first. Confirm these really are the awkward moments in the video.\n")
    w("(A length shown as 0.30 is just under 0.3 s.)\n")
    amb = ev[(ev["duration_s"] < 0.3) | (ev["mean_confidence"] < 0.7)]
    w("| Take | Phase | Start (s) | End (s) | Length (s) | Confidence | Seen: brief or hard to call? (Y/N) |\n|---|---|---|---|---|---|---|")
    for r in amb.itertuples():
        w(f"| {r.take} | {r.label} | {f(r.start_s)} | {f(r.end_s)} | {f(r.duration_s)} | {r.mean_confidence:.2f} | |")
    w("\nAlso answer: **is vid5 the take that was hardest to perform and to label?** Seen: ______ (it contains the hesitation, failed grasp and occlusion cycles, so it should be).\n")

    w("## E. Query 5: where the detected phase disagrees most with the labels\n")
    q5 = pd.read_csv(ROOT / "snowflake" / "expected_results" / "q5_prediction_agreement_by_label.csv").sort_values(["agreement", "take", "label"]).head(4)
    w("Lowest agreement per take and phase (query 5): " + ", ".join(f"{r.take} {r.label} {r.agreement:.2f}" for r in q5.itertuples()) + ".\n")
    reach = gt[(gt["take"] == "vid5") & (gt["cycle"] == 3) & (gt["label"] == "REACH")].iloc[0]
    det = ev[(ev["take"] == "vid5") & (ev["label"] == "GRASP") & (ev["start_s"] > reach["start_s"]) & (ev["start_s"] < reach["end_s"])]
    w("| Check | Where | What you should see | Seen |\n|---|---|---|---|")
    if len(det):
        d = det.iloc[0]
        w(f"| vid5 REACH read as GRASP too early | hand-labelled REACH {f(reach['start_s'])} to {f(reach['end_s'])} s; detected GRASP starts {f(d['start_s'])} s | between {f(d['start_s'])} and {f(reach['end_s'])} s the hand is still approaching or lingering at the object and the fingers have **not yet started closing** (so the detector is wrong, the label is right) | |")
    w("| vid4 RELEASE never detected | see C3 | a short release exists in each fast cycle | |")
    w("")

    w("## F. Sign-off\n")
    w("Tick one and add notes, then send me the filled-in tables (or just the Y/N answers and anything surprising).\n")
    w("- [ ] Results make sense: cycle times, durations and orders match the videos, and every disagreement is one of the known ones above.")
    w("- [ ] Some results do NOT match the video (list them: take, time, what you saw). This is a finding to investigate, not a failure of the Snowflake run.\n")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    out = ROOT / "snowflake" / "sanity_check_checklist.md"
    out.write_text(build())
    print("wrote", out)
